export const GENRES = {
    aa: "Action / Adventure",
    ht: "Horror / Thriller",
    cs: "Comedy / Satire",
    dr: "Drama / Romance",
};

export const RATINGS = {
    e: "E: Everyone",
    pg: "PG-13: 13+ Only",
    a: "A: Adult Only",
}

export const LENGTHS = {
    short: "2 Hours or Less",
    long: "More Than 2 Hours",
};

export const MOVIES = {
    Night_At_The_Museum: {g: "aa", r: "e", l: "short",},
    Spiderman: {g: "aa", r: "e", l: "short",},
    Guardians_of_the_Galaxy: {g: "aa", r: "e", l: "short",},
    The_Chronicles_of_Narnia: {g: "aa", r: "e", l: "long",},
    The_Secret_Life_of_Walter_Mitty: {g: "aa", r: "e", l: "long",},
    Pirates_of_the_Carribean: {g: "aa", r: "e", l: "long",},
    Carry_On: {g: "aa", r: "pg", l: "short",},
    Transformers: {g: "aa", r: "pg", l: "short",},
    Jurassic_World: {g: "aa", r: "pg", l: "short",},
    Tenet: {g: "aa", r: "pg", l: "long",},
    Jurassic_Park: {g: "aa", r: "pg", l: "long",},
    The_Avengers: {g: "aa", r: "pg", l: "long",},
    Extraction: {g: "aa", r: "a", l: "short",},
    The_Dark_Knight: {g: "aa", r: "a", l: "short",},
    Mad_Max: {g: "aa", r: "a", l: "short",},
    Six_Underground: {g: "aa", r: "a", l: "long",},
    Wonder_Woman: {g: "aa", r: "a", l: "long",},
    The_Justice_League: {g: "aa", r: "a", l: "long",},
    Coraline: {g: "ht", r: "e", l: "short",},
    The_Visit: {g: "ht", r: "e", l: "short",},
    The_Others: {g: "ht", r: "e", l: "short",},
    Haunted_Mansion: {g: "ht", r: "e", l: "long",},
    Poltergeist: {g: "ht", r: "e", l: "long",},
    The_Babadook: {g: "ht", r: "e", l: "long",},
    A_Quiet_Place: {g: "ht", r: "pg", l: "short",},
    Insidious: {g: "ht", r: "pg", l: "short",},
    The_Sixth_Sense: {g: "ht", r: "pg", l: "short",},
    The_Mummy: {g: "ht", r: "pg", l: "long",},
    The_Purge: {g: "ht", r: "pg", l: "long",},
    The_Stranger: {g: "ht", r: "pg", l: "long",},
    Eli: {g: "ht", r: "a", l: "short",},
    Hereditary: {g: "ht", r: "a", l: "short",},
    It_Follows: {g: "ht", r: "a", l: "short",},
    Bird_Box: {g: "ht", r: "a", l: "long",},
    The_Conjuring: {g: "ht", r: "a", l: "long",},
    It: {g: "ht", r: "a", l: "long",},
    Shrek: {g: "cs", r: "e", l: "short",},
    The_Intern: {g: "cs", r: "e", l: "short",},
    The_Proposal: {g: "cs", r: "e", l: "short",},
    Mrs_Doubtfire: {g: "cs", r: "e", l: "long",},
    The_Guardian: {g: "cs", r: "e", l: "long",},
    Step_Brothers: {g: "cs", r: "e", l: "long",},
    Lift: {g: "cs", r: "pg", l: "short",},
    Anchorman: {g: "cs", r: "pg", l: "short",},
    Superbad: {g: "cs", r: "pg", l: "short",},
    The_Fall_Guy: {g: "cs", r: "pg", l: "long",},
    The_Hunger_Games: {g: "cs", r: "pg", l: "long",},
    The_Mist: {g: "cs", r: "pg", l: "long",},
    Grown_Ups: {g: "cs", r: "a", l: "short",},
    Bad_Santa: {g: "cs", r: "a", l: "short",},
    Tropic_Thunder: {g: "cs", r: "a", l: "short",},
    The_Wolf_of_Wall_Street: {g: "cs", r: "a", l: "long",},
    Deadpool: {g: "cs", r: "a", l: "long",},
    Thats_My_Boy: {g: "cs", r: "a", l: "long",},
    A_Cinderella_Story: {g: "dr", r: "e", l: "short",},
    The_Vow: {g: "dr", r: "e", l: "short",},
    Notting_Hill: {g: "dr", r: "e", l: "short",},
    Beauty_and_the_Beast: {g: "dr", r: "e", l: "long",},
    Before_Sunrise: {g: "dr", r: "e", l: "long",},
    When_Harry_Met_Sally: {g: "dr", r: "e", l: "long",},
    Love_at_First_Sight: {g: "dr", r: "pg", l: "short",},
    The_Lucky_One: {g: "dr", r: "pg", l: "short",},
    Ten_Things_I_Hate_About_You: {g: "dr", r: "pg", l: "short",},
    Titanic: {g: "dr", r: "pg", l: "long",},
    A_Star_is_Born: {g: "dr", r: "pg", l: "long",},
    La_La_Land: {g: "dr", r: "pg", l: "long",},
    Last_Summer: {g: "dr", r: "a", l: "short",},
    Romeo_and_Juliet: {g: "dr", r: "a", l: "short",},
    Legally_Blonde: {g: "dr", r: "a", l: "short",},
    Fifty_Shades_of_Grey: {g: "dr", r: "a", l: "long",},
    Blue_is_the_Warmest_Color: {g: "dr", r: "a", l: "long",},
    Call_Me_By_Your_Name: {g: "dr", r: "a", l: "long",},
}